-- Regenerează `supabase/schema/runlift.sql` — instantaneul schemei din producție.
--
-- CÂND: după fiecare migrare aplicată pe `runlift`. Testele SQL
-- (`tests/unit/sql/*.test.ts`) rulează pe instantaneu, deci un instantaneu vechi
-- înseamnă teste care păzesc altceva decât ce rulează live.
--
-- CUM: rulează interogarea (MCP `execute_sql` sau SQL Editor) și scrie coloana
-- `ddl` peste `supabase/schema/runlift.sql`, sub antetul existent. Rezultatul e
-- de ordinul a 90 KB, deci MCP-ul îl salvează într-un fișier — de acolo se
-- copiază.
--
-- Ordinea din ieșire e cea în care se poate REÎNCĂRCA: funcțiile înaintea
-- tabelelor (coloanele au `default current_event_edition()`), cheile primare
-- înaintea celor externe, triggerele la final. Rolurile, `pgcrypto` și dublul de
-- `net.http_post` NU sunt aici — le pune `tests/unit/sql/db.ts`, fiindcă țin de
-- infrastructura Supabase, nu de schema noastră.

with functii as (
  select string_agg(pg_get_functiondef(p.oid) || E';\n', E'\n' order by p.proname) t
    from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'runlift'
), coloane as (
  select c.relname, string_agg('  ' || quote_ident(a.attname) || ' ' || format_type(a.atttypid, a.atttypmod)
       || case when a.attidentity = 'a' then ' generated always as identity'
               when a.attidentity = 'd' then ' generated by default as identity'
               else coalesce(' default ' || pg_get_expr(d.adbin, d.adrelid), '') end
       || case when a.attnotnull then ' not null' else '' end, E',\n' order by a.attnum) cols
    from pg_class c join pg_namespace n on n.oid = c.relnamespace
    join pg_attribute a on a.attrelid = c.oid and a.attnum > 0 and not a.attisdropped
    left join pg_attrdef d on d.adrelid = c.oid and d.adnum = a.attnum
   where n.nspname = 'runlift' and c.relkind = 'r' group by c.relname
), tabele as (
  select string_agg('create table runlift.' || quote_ident(relname) || E' (\n' || cols || E'\n);\n', E'\n' order by relname) t from coloane
), constrangeri as (
  -- Întâi cheile primare și unice: cele externe le referă.
  select string_agg('alter table runlift.' || quote_ident(c.relname) || ' add constraint ' || quote_ident(con.conname)
       || ' ' || pg_get_constraintdef(con.oid) || E';\n', ''
       order by case when con.contype in ('p', 'u') then 0 else 1 end, c.relname, con.conname) t
    from pg_constraint con join pg_class c on c.oid = con.conrelid join pg_namespace n on n.oid = c.relnamespace
   where n.nspname = 'runlift'
), indexuri as (
  select coalesce(string_agg(pg_get_indexdef(i.indexrelid) || E';\n', '' order by i.indexrelid::regclass::text), '') t
    from pg_index i join pg_class c on c.oid = i.indrelid join pg_namespace n on n.oid = c.relnamespace
   where n.nspname = 'runlift' and not exists (select 1 from pg_constraint con where con.conindid = i.indexrelid)
), triggere as (
  select string_agg(pg_get_triggerdef(t.oid) || E';\n', '' order by t.tgname) t
    from pg_trigger t join pg_class c on c.oid = t.tgrelid join pg_namespace n on n.oid = c.relnamespace
   where n.nspname = 'runlift' and not t.tgisinternal
), roluri as (select unnest(array['anon', 'authenticated', 'service_role']) r
), drepturi_functii as (
  -- Postgres acordă implicit EXECUTE tuturor, deci starea „revocată" se scrie explicit.
  select string_agg(
    'revoke all on function runlift.' || quote_ident(p.proname) || '(' || pg_get_function_identity_arguments(p.oid) || ') from public, anon, authenticated, service_role;' ||
    coalesce((select string_agg(E'\ngrant execute on function runlift.' || quote_ident(p.proname) || '(' || pg_get_function_identity_arguments(p.oid) || ') to ' || r || ';', '')
       from roluri where has_function_privilege(r, p.oid, 'execute')), ''), E'\n' order by p.proname) t
    from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'runlift'
), drepturi_tabele as (
  select string_agg(
    'revoke all on table runlift.' || quote_ident(c.relname) || ' from public, anon, authenticated, service_role;' ||
    coalesce((select string_agg(E'\ngrant ' || pr || ' on table runlift.' || quote_ident(c.relname) || ' to ' || r || ';', '')
      from roluri, unnest(array['select', 'insert', 'update', 'delete']) pr
      where has_table_privilege(r, c.oid, pr)), '') ||
    case when c.relrowsecurity then E'\nalter table runlift.' || quote_ident(c.relname) || ' enable row level security;' else '' end,
    E'\n' order by c.relname) t
    from pg_class c join pg_namespace n on n.oid = c.relnamespace where n.nspname = 'runlift' and c.relkind = 'r'
), politici as (
  select coalesce(string_agg('create policy ' || quote_ident(p.policyname) || ' on runlift.' || quote_ident(p.tablename)
    || ' as ' || p.permissive || ' for ' || p.cmd || ' to ' || array_to_string(p.roles, ', ')
    || coalesce(' using (' || p.qual || ')', '') || coalesce(' with check (' || p.with_check || ')', '') || ';', E'\n'
    order by p.tablename, p.policyname), '') t
  from pg_policies p where p.schemaname = 'runlift'
)
select (select t from functii) || E'\n' || (select t from tabele) || E'\n'
    || (select t from constrangeri) || E'\n' || (select t from indexuri) || E'\n' || (select t from triggere)
    || E'\n' || (select t from drepturi_functii) || E'\n\n' || (select t from drepturi_tabele)
    || E'\n\n' || (select t from politici) || E'\n' as ddl;
